security:
  
  providers:
    in_memory:
        memory: ~

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: ~

  access_control:
  # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
  # toutes les url qui commencent par /admin requièrent le rôle admin
    - { path: ^/admin, roles: ROLE_ADMIN }
